"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

try:
    from decouple import Csv, config
except ImportError:  # pragma: no cover
    def config(key, default=None, cast=str):
        value = os.environ.get(key, default)
        if value is None:
            return None
        if cast is bool:
            return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}
        if cast:
            return cast(value)
        return value

    class Csv:
        def __call__(self, value):
            return [item.strip() for item in str(value).split(',') if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def _strip_env_value(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value


# Load .env into process environment without extra dependencies.
ENV_PATH = BASE_DIR / ".env"
if ENV_PATH.exists():
    for line in ENV_PATH.read_text(encoding="utf-8-sig").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), _strip_env_value(value))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEVELOPMENT_SECRET_KEY = "sklint-dev-only-secret-key-change-me-before-production-2026"
SECRET_KEY = config('DJANGO_SECRET_KEY', default=DEVELOPMENT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('DJANGO_CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default='').strip()
if RENDER_EXTERNAL_HOSTNAME:
    if RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

    render_origin = f'https://{RENDER_EXTERNAL_HOSTNAME}'
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

SECURE_SSL_REDIRECT = config('DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = config('DJANGO_SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config('DJANGO_CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
SECURE_HSTS_SECONDS = config('DJANGO_SECURE_HSTS_SECONDS', default=31536000 if not DEBUG else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=not DEBUG,
    cast=bool,
)
SECURE_HSTS_PRELOAD = config('DJANGO_SECURE_HSTS_PRELOAD', default=not DEBUG, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_CONTENT_TYPE_NOSNIFF = config('DJANGO_SECURE_CONTENT_TYPE_NOSNIFF', default=True, cast=bool)
SECURE_REFERRER_POLICY = config('DJANGO_SECURE_REFERRER_POLICY', default='same-origin')
X_FRAME_OPTIONS = config('DJANGO_X_FRAME_OPTIONS', default='DENY')

if not DEBUG:
    if SECRET_KEY == DEVELOPMENT_SECRET_KEY:
        raise ImproperlyConfigured('Set DJANGO_SECRET_KEY before running with DJANGO_DEBUG=false.')
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured('Set DJANGO_ALLOWED_HOSTS before running with DJANGO_DEBUG=false.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clints',
    'coderoast',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'project.appid.AppIDRequiredMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'project.appid.appid_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'statics',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

GOOGLE_AI_STUDIO_API_KEY = config(
    'GOOGLE_AI_STUDIO_API_KEY',
    default=config('GEMINI_API_KEY', default=''),
)
GOOGLE_AI_MODEL = config(
    'CODEROAST_GEMINI_MODEL',
    default=config('GOOGLE_AI_MODEL', default='gemini-2.5-flash'),
)
CODEROAST_TTS_PROVIDER = config('CODEROAST_TTS_PROVIDER', default='browser')
SARVAM_API_KEY = config('SARVAM_API_KEY', default='')
SARVAM_TTS_MODEL = config('SARVAM_TTS_MODEL', default='bulbul:v3')
SARVAM_TTS_AUDIO_CODEC = config('SARVAM_TTS_AUDIO_CODEC', default='mp3')
SARVAM_TTS_ENGLISH_SPEAKER = config('SARVAM_TTS_ENGLISH_SPEAKER', default='')
SARVAM_TTS_HINDI_SPEAKER = config('SARVAM_TTS_HINDI_SPEAKER', default='')
SARVAM_TTS_TELUGU_SPEAKER = config('SARVAM_TTS_TELUGU_SPEAKER', default='')
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())

CLOUDANT_ASSETS_ENABLED = config('CLOUDANT_ASSETS_ENABLED', default=False, cast=bool)
CLOUDANT_URL = config('CLOUDANT_URL', default='').rstrip('/')
CLOUDANT_DATABASE = config('CLOUDANT_DATABASE', default='')
CLOUDANT_USERNAME = config('CLOUDANT_USERNAME', default='')
CLOUDANT_PASSWORD = config('CLOUDANT_PASSWORD', default='')
CLOUDANT_BEARER_TOKEN = config('CLOUDANT_BEARER_TOKEN', default='')
CLOUDANT_ASSET_GROUP = config('CLOUDANT_ASSET_GROUP', default='coderoast')

APPID_API_KEY = config('APPID_API_KEY', default='')
APPID_CLIENT_ID = config('APPID_CLIENT_ID', default='')
APPID_CLIENT_SECRET = config('APPID_CLIENT_SECRET', default='')
APPID_TENANT_ID = config('APPID_TENANT_ID', default='')
APPID_SERVICE_ENDPOINT = config('APPID_SERVICE_ENDPOINT', default='')
APPID_DISCOVERY_ENDPOINT = config('APPID_DISCOVERY_ENDPOINT', default='')
APPID_OAUTH_SERVER_URL = config('APPID_OAUTH_SERVER_URL', default='')
APPID_MANAGEMENT_URL = config('APPID_MANAGEMENT_URL', default='')
APPID_SCOPE = config('APPID_SCOPE', default='openid email profile')
APPID_REQUIRE_LOGIN = config('APPID_REQUIRE_LOGIN', default=False, cast=bool)
APPID_PROTECTED_PATH_PREFIXES = config(
    'APPID_PROTECTED_PATH_PREFIXES',
    default='/,/about/,/projects/,/contact/',
    cast=Csv(),
)
APPID_EXEMPT_PATH_PREFIXES = config(
    'APPID_EXEMPT_PATH_PREFIXES',
    default='',
    cast=Csv(),
)

